### ISSUE TITLE
Transport: nodes that are down cause nil pointer dereference 

### ISSUE THREAD

**Issue by Choraden** [scylladb/scylla-go-driver#222]
Calling LeastBusyConn on a Node that is down results in panic! 
It happens when for the first time node is added to known topology in Cluster::refreshTopology()

**Comment by Kulezi** [comment]
Probably caused by the same issue, found running integration tests.
```
 --- FAIL: TestContextsIntegration (0.26s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6334f0]

goroutine 3364 [running]:
testing.tRunner.func1.2({0x674980, 0x889e30})
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1399 +0x39f
panic({0x674980, 0x889e30})
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
github.com/scylladb/scylla-go-driver/transport.(*Conn).Waiting(...)
	/home/runner/work/scylla-go-driver/scylla-go-driver/transport/conn.go:777
github.com/scylladb/scylla-go-driver/transport.(*Conn).sendController(0x162f40?, {0x72a408?, 0xc000098800?})
	/home/runner/work/scylla-go-driver/scylla-go-driver/transport/conn.go:747 +0x50
github.com/scylladb/scylla-go-driver/transport.(*Conn).sendRequest(0x0, {0x72a408, 0xc000098800}, {0x729638, 0xc000140510}, 0x0, 0x0)
	/home/runner/work/scylla-go-driver/scylla-go-driver/transport/conn.go:682 +0x66
github.com/scylladb/scylla-go-driver/transport.(*Conn).Execute(_, {_, _}, {{0xc0009eaaf0, 0x10, 0x10}, {0x6bdafb, 0x25}, {0xc000998440, 0x1, ...}, ...}, ...)
	/home/runner/work/scylla-go-driver/scylla-go-driver/transport/conn.go:647 +0x235
github.com/scylladb/scylla-go-driver.(*Session).Prepare.func2({_, _}, _, {{0xc0009eaaf0, 0x10, 0x10}, {0x6bdafb, 0x25}, {0xc000998440, 0x1, ...}, ...}, ...)
	/home/runner/work/scylla-go-driver/scylla-go-driver/session.go:184 +0xb5
github.com/scylladb/scylla-go-driver.(*Query).Exec(0xc000163be8, {0x72a408, 0xc000098800})
	/home/runner/work/scylla-go-driver/scylla-go-driver/query.go:35 +0x3c4
github.com/scylladb/scylla-go-driver.TestContextsIntegration(0xc000241d40)
	/home/runner/work/scylla-go-driver/scylla-go-driver/session_integration_test.go:480 +0x956
testing.tRunner(0xc000241d40, 0x6dcce0)
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1493 +0x35f
make: *** [Makefile:65: docker-integration-test] Error 2
```
